### ISSUE TITLE
SSList causes a NullPointerException when value in database is null

### ISSUE THREAD

**Issue by prasanthreddy-git** [bpangburn/swingset#133]
SSList causes a NullPointerException when the value in the database is null

java.lang.NullPointerException: null
at com.nqadmin.swingset.models.SSDbArrayModel.readData(SSDbArrayModel.java:90) ~[swingset-4.1.0-SNAPSHOT.jar:?]
at com.nqadmin.swingset.SSList.updateSSComponent(SSList.java:539) ~[swingset-4.1.0-SNAPSHOT.jar:?]
at com.nqadmin.swingset.utils.SSCommon.updateSSComponent(SSCommon.java:1039) ~[swingset-4.1.0-SNAPSHOT.jar:?]
at com.nqadmin.swingset.utils.SSCommon.bind(SSCommon.java:526) ~[swingset-4.1.0-SNAPSHOT.jar:?]
at com.nqadmin.swingset.utils.SSCommon.bind(SSCommon.java:554) ~[swingset-4.1.0-SNAPSHOT.jar:?]
at com.nqadmin.swingset.utils.SSCommon.bind(SSCommon.java:568) ~[swingset-4.1.0-SNAPSHOT.jar:?]
at com.nqadmin.swingset.utils.SSComponentInterface.bind(SSComponentInterface.java:130) ~[swingset-4.1.0-SNAPSHOT.jar:?]

**Comment by prasanthreddy-git** [comment]
Checking if the object list is null before converting it into an array

**Comment by bpangburn** [comment]
Should be fixed in SwingSet 4.0.10
