### ISSUE TITLE
SSDateField bind fails when there are no records in the rowset

### ISSUE THREAD

**Issue by prasanthreddy-git** [bpangburn/swingset#140]
org.postgresql.util.PSQLException: ResultSet not positioned properly, perhaps you need to call next.
        at org.postgresql.jdbc.PgResultSet.getRawValue(PgResultSet.java:3137) ~[postgresql-42.3.4.jar:42.3.4]
        at org.postgresql.jdbc.PgResultSet.getObject(PgResultSet.java:2911) ~[postgresql-42.3.4.jar:42.3.4]
        at com.nqadmin.rowset.JdbcRowSetImpl.getObject(JdbcRowSetImpl.java:1647) ~[jdbcrowsetimpl-1.0.3.jar:?]
        at com.nqadmin.rowset.JdbcRowSetImpl.getObject(JdbcRowSetImpl.java:1678) ~[jdbcrowsetimpl-1.0.3.jar:?]
        at com.nqadmin.swingset.formatting.SSFormattedTextField.updateSSComponent(SSFormattedTextField.java:519) ~[swingset-4.0.10-SNAPSHOT.jar:?]
        at com.nqadmin.swingset.utils.SSCommon.updateSSComponent(SSCommon.java:1039) ~[swingset-4.0.10-SNAPSHOT.jar:?]
        at com.nqadmin.swingset.utils.SSCommon.bind(SSCommon.java:526) ~[swingset-4.0.10-SNAPSHOT.jar:?]
        at com.nqadmin.swingset.utils.SSCommon.bind(SSCommon.java:554) ~[swingset-4.0.10-SNAPSHOT.jar:?]
        at com.nqadmin.swingset.utils.SSCommon.bind(SSCommon.java:568) ~[swingset-4.0.10-SNAPSHOT.jar:?]
        at com.nqadmin.swingset.utils.SSComponentInterface.bind(SSComponentInterface.java:130) ~[swingset-4.0.10-SNAPSHOT.jar:?]

**Comment by bpangburn** [comment]
@prasanthreddy-git added a check for zero records with the following commit on 2022-05-09:
https://github.com/bpangburn/swingset/commit/e1d38b3
