### ISSUE TITLE
SSTextField with date mask is throwing exceptions for each key pressed event

### ISSUE THREAD

**Issue by bpangburn** [bpangburn/swingset#141]
```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException
    at java.sql/java.sql.Date.valueOf(Date.java:141)
    at com.nqadmin.swingset.datasources.RowSetOps.updateColumnText(RowSetOps.java:483)
    at com.nqadmin.swingset.utils.SSCommon.setBoundColumnText(SSCommon.java:972)
    at com.nqadmin.swingset.utils.SSCommon$SSDocumentListener.lambda$1(SSCommon.java:160)
    at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
    at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
    at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
    at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by bpangburn** [comment]
Per @prasanthreddy-git the else condition for processing dates in RowSetOps (near line 476) is likely causing this issue and should just be commented out:

```
		case DATE:
// TODO Good to get rid of getSQLDate if possible.
			if (_updatedValue.length() == 10) {
				Date dateValue = SSCommon.getSQLDate(_updatedValue);
				_rowSet.updateDate(_columnName, dateValue);
			} else {
			// 2020-12-01_BP: Might as well at least try to process a date that is other than 10 characters
				Date dateValue = java.sql.Date.valueOf(_updatedValue);
				_rowSet.updateDate(_columnName, dateValue);
			}
			break;
```
