### ISSUE TITLE
Failed to copy data in data grid

### ISSUE THREAD

**Issue by prasanthreddy-git** [bpangburn/swingset#89]
Unable to copy data when dates are involved. Below is the exception. 

 2021-03-18 13:09:02 [ WARN] No Such Method Exception. Failed to copy data.
java.lang.NoSuchMethodException: java.sql.Date.<init>(java.lang.String)
at java.lang.Class.getConstructor0(Class.java:3082) ~[?:1.8.0_282]
at java.lang.Class.getConstructor(Class.java:1825) ~[?:1.8.0_282]
at com.nqadmin.swingset.SSTableKeyAdapter.getObjectToSet(SSTableKeyAdapter.java:100) [swingset-4.0.4-SNAPSHOT.jar:?]
at com.nqadmin.swingset.SSTableKeyAdapter.keyReleased(SSTableKeyAdapter.java:335) [swingset-4.0.4-SNAPSHOT.jar:?]
at java.awt.AWTEventMulticaster.keyReleased(AWTEventMulticaster.java:260) [?:1.8.0_282]
at java.awt.Component.processKeyEvent(Component.java:6500) [?:1.8.0_282]
at javax.swing.JComponent.processKeyEvent(JComponent.java:2832) [?:1.8.0_282]
at java.awt.Component.processEvent(Component.java:6316) [?:1.8.0_282]
at java.awt.Container.processEvent(Container.java:2239) [?:1.8.0_282]
at java.awt.Component.dispatchEventImpl(Component.java:4889) [?:1.8.0_282]
at java.awt.Container.dispatchEventImpl(Container.java:2297) [?:1.8.0_282]
at java.awt.Component.dispatchEvent(Component.java:4711) [?:1.8.0_282]
at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954) [?:1.8.0_282]
at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:834) [?:1.8.0_282]
at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1102) [?:1.8.0_282]
at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:973) [?:1.8.0_282]
at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:799) [?:1.8.0_282]
at java.awt.Component.dispatchEventImpl(Component.java:4760) [?:1.8.0_282]
at java.awt.Container.dispatchEventImpl(Container.java:2297) [?:1.8.0_282]
at java.awt.Window.dispatchEventImpl(Window.java:2746) [?:1.8.0_282]
at java.awt.Component.dispatchEvent(Component.java:4711) [?:1.8.0_282]
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760) [?:1.8.0_282]
at java.awt.EventQueue.access$500(EventQueue.java:97) [?:1.8.0_282]
at java.awt.EventQueue$3.run(EventQueue.java:709) [?:1.8.0_282]
at java.awt.EventQueue$3.run(EventQueue.java:703) [?:1.8.0_282]
at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_282]
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) [?:1.8.0_282]
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84) [?:1.8.0_282]
at java.awt.EventQueue$4.run(EventQueue.java:733) [?:1.8.0_282]
at java.awt.EventQueue$4.run(EventQueue.java:731) [?:1.8.0_282]
at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_282]
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) [?:1.8.0_282]
at java.awt.EventQueue.dispatchEvent(EventQueue.java:730) [?:1.8.0_282]
at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205) [?:1.8.0_282]
at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_282]
at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_282]
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_282]
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_282]
at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_282]

**Comment by prasanthreddy-git** [comment]
When converting from string to object we are using constructors of the underlying column type. In the case of java.sql.Date there is no constructor that would take a date in string format. We have to use Date.valueOf for converting string to Date object.

**Comment by prasanthreddy-git** [comment]
Below is the change made to the code
`if (_value != null) {
				// DATE CLASS DOESN'T HAVE A CONSTRUCTOR THAT TAKES A STRING
				if(objectClass.equals(java.sql.Date.class)) {
					newValue = Date.valueOf(_value);
				}
				else {
					// GET THE CONSTRUCTOR FOR THE CLASS WHICH TAKES A STRING
					final Constructor<?> constructor = objectClass.getConstructor(new Class<?>[] { String.class });
	
					// CREATE AN INSTANCE OF THE OBJECT
					newValue = constructor.newInstance(new Object[] { _value });
				}
			}`
